services:
  # sql:
  #   image: mcr.microsoft.com/azure-sql-edge:latest
  #   environment:
  #     ACCEPT-EULA: "1"
  #     MSSQL_SA_PASSWORD: "Password@1"
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sql-data:/var/opt/mssql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  sql-data:
  redis-data: